### ISSUE TITLE
Why export the same components from this module?

### ISSUE THREAD

**Issue by abhiaiyer91** [phrase/react-intl-phraseapp#1]
I really like this integration and use phrase app in my startup. I was hoping I could get more intuition on why this library has its own exports for React intl components. In my opinion this is a tight coupling between React intl users and phrase app. Is there a way we could use this library without the special components?

**Comment by timleers** [comment]
Hi @abhiaiyer91,
thanks for your feedback! We are at the very beginning of learning react & react-intl and therefor happy about any advises.
After a day of trying to hook into the lifecycle of the react-intl components only this approach was successful. If you have any other approach feel free to tell us about.

**Comment by theSoenke** [comment]
We now support the `translate` and `formatMessage` directly on props. Here is an example to use it: https://github.com/phrase/react-intl-phraseapp-demo/blob/master/src/App.js
