### ISSUE TITLE
Bugfix/Problem with new version Typescript

### ISSUE THREAD

**Issue by MylesWardell** [phrase/react-intl-phraseapp#103]
This is testing the new version example folder because i was experiencing the same issue on my project

![image](https://github.com/phrase/react-intl-phraseapp/assets/55673046/0e9b2a8e-f04d-4772-b12a-70c8818c31ef)

Here are the dependencies
```json
"dependencies": {
    "@types/jest": "^29.5.4",
    "@types/node": "^20.5.7",
    "@types/react": "^18.2.21",
    "@types/react-dom": "^18.2.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-intl": "^6.4.4",
    "react-intl-phraseapp": "^4.1.0",
    "react-scripts": "5.0.1",
    "typescript": "^5.2.2"
  },
  "devDependencies": {
    "@tsconfig/create-react-app": "^2.0.1"
  },
```

Tested using node v18.X.X

**Comment by Varpusparvi** [comment]
@MylesWardell Fixed in `4.1.2`. Please try it out and get back to us if you still run into any problems. Sorry for the inconvenience!
