### ISSUE TITLE
Bug in hidden elements

### ISSUE THREAD

**Issue by reifter** [phrase/react-intl-phraseapp#108]
**Expected behavior**
Hidden menu list does not have edit buttons
<img width="285" alt="image" src="https://github.com/phrase/react-intl-phraseapp/assets/3066623/b7cfbb71-133b-441a-9177-faef38b3212a">
If the menu is expanded, the buttons are displayed
<img width="348" alt="image" src="https://github.com/phrase/react-intl-phraseapp/assets/3066623/96c8e30a-09b2-46c7-aa62-4860de566d9f">

**Actual behavior**
The menu list is hidden initially, but we have edit buttons for all hidden menu items. This behavior degrades the interface

<img width="739" alt="image" src="https://github.com/phrase/react-intl-phraseapp/assets/3066623/dae99d96-8118-4676-ae10-3a7b1dd0fe02">

**Your environment**
The bug is reproduced in any browser and operating system

**Steps to reproduce the problem**
If we use an old version (useOldICE: true option is enabled) - the bug is not reproduced

**Comment by itsahsiao** [comment]
Hi @reifter, happy new year!

Thanks so much for reporting this! We'll take a look into it and see what we can do to fix this.

**Comment by Varpusparvi** [comment]
@itsahsiao We might have to add some kind of checking if some parent element of the string is hidden, but might be tricky / slow on a heavy page 🤔

**Comment by itsahsiao** [comment]
@reifter: @Varpusparvi and I had a quick look yesterday and we can confirm that we have this logic in the old version of the In-Context Editor. 

We've added this issue onto our roadmap and will fix it in the coming weeks. We'll keep you posted.

**Comment by reifter** [comment]
Hi @itsahsiao, Is there any update?

**Comment by itsahsiao** [comment]
Hi @reifter, this issue is in our active sprint right now and one of our devs is picking it up and will update shortly. Thanks for your patience.

**Comment by lookasc** [comment]
Hi @reifter,
We've deployed a fix. Can you verify it and let us know if the reported issue is resolved for you?

**Comment by reifter** [comment]
Hi @lookasc,
Thank you for implementing the fix. The display of control buttons in hidden elements is indeed working now. However, when hovering over the button, it promptly disappears, making it challenging to click. 
I think the button shouldn't hide when the cursor is on it.


https://github.com/phrase/react-intl-phraseapp/assets/3066623/10a9c0dc-5cdc-46d5-830f-385d840403df

**Comment by lookasc** [comment]
Hi @reifter,
Thank you, I'll take another look at it.

**Comment by lookasc** [comment]
Hi @reifter, another fix has been deployed. Can you verify again?

**Comment by reifter** [comment]
Hi @lookasc, great job, thank you! Now it works, and the workflow has become more convenient.
