### ISSUE TITLE
Remove the phrase prefix

### ISSUE THREAD

**Issue by hudovisk** [phrase/react-intl-phraseapp#12]
Can we have an option in the config object to remove the hardcoded `phrase_` prefix ?

https://github.com/phrase/react-intl-phraseapp/blob/275c7e410c6800e42856c90ed97b80cdeb491c67/src/functions.ts#L37

**Comment by theSoenke** [comment]
Could you describe your use case for this? Without the `phrase_` prefix the InContext-Editor will not able to detect keys on the page anymore

**Comment by hudovisk** [comment]
The problem is we already have a format for the messages id and don't want to have to use the prefix. Can't we somehow use the exported `<FormattedMessage />` from the package to detect it without change the id's of the messages?

**Comment by theSoenke** [comment]
The prefix is only used for the InContext-Editor to detect keys on the page and to be able to translate them. Without the prefix the InContext-Editor can't work anymore. This prefix also does require no manual change of the key names from your side and should work with all existing keys.

We also recommend to only use this package in a preview/staging environment where the InContext-Editor is used to translate the application. In all other environments you can directly use the `react-intl` package. Does this clarifies it maybe a bit?

**Comment by hudovisk** [comment]
I should conditionally import the component based on node_env ? Like, every time I use `<FormattedMessage />` I have to check if I am on staging or production?

**Comment by theSoenke** [comment]
Yes, this would require a conditional import for `FormattedMessage`. You can also set  `phraseEnabled: false` in the config but we recommend to directly use `react-intl` in production

**Comment by theSoenke** [comment]
@hudovisk I will close this for now. Let me know if you still have any question
