### ISSUE TITLE
Working with babel-plugin-react-intl

### ISSUE THREAD

**Issue by Bazze** [phrase/react-intl-phraseapp#2]
Hello!

Thanks for this package, it's really helpful. However, we're using [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl) for generating translations and when starting to use this package all translations are not extracted correctly. This is caused by the babel plugin only extracting translations coming from the exactly named package `react-intl`, which can be changed to `react-intl-phraseapp` through the `moduleSourceName` configuration option. But this only solves the issue for extracting translations from `FormattedMessage` and `FormattedHTMLMessage`, since that are the only components that this package is exporting. We are also heavily using the `defineMessages` function from `react-intl` in our applications.

I see multiple solutions:

1. This package exports everything from the `react-intl` package, where we override the Formatted* components with the wrapped ones in this package
2. We suggest to the `react-intl` people that the `moduleSourceName` configuration option should be able to match multiple package names

Would love your input on this.

Thanks

**Comment by timleers** [comment]
Hi @Bazze,
thanks for your feedback. Probably the second would be the best solution but maybe the 'react-intl' guys don't see the need to implement that feature. 
If so it should be no problem to export every relevant component via this package as there aren't that many.
Bests,
Tim from PhraseApp

**Comment by Bazze** [comment]
Hello @timleers! I'm not sure that I agree that it's the best option, if you are to wrap the `react-intl` library I think it would be cleaner to wrap it completely rather than a few parts as it is now. Then you can wrap what's needed and the rest can just be exported as is.

Anyway, I will raise an issue over at `react-intl` as well and see what they think about it.

**Comment by timleers** [comment]
Your argument is quite comprehensible. I will discuss that in the team. Thanks!

**Comment by jameschao** [comment]
Hi, what do you think about hooking into `defineMessages` as a way to extract messages rather than via `FormattedMessage`?

I came across this description of `defineMessage` on https://github.com/yahoo/react-intl/wiki/API:
> This function is exported by the react-intl package and is simply a hook for the babel-plugin-react-intl package to use when extracting default messages defined in JavaScript source files. 

I haven't looked into the mechanics of it, but it just seems like this hook could be an easy to extract all the strings.

**Comment by timleers** [comment]
Hi @jameschao,
thanks for your feedback. This might be way better and we will have a look into it. But it will take some time. If you like you can try it and make a pull request :)
We will keep this up to date as soon as we have any progress.

**Comment by BobReid** [comment]
overriding reactintl components seems like a cumbersome solution. We use formatted message as much as possible but there are times we have to use other methods like when there is a dropdown, input placeholders, or maybe a view model has a localization in it. 

My workaround was to just transform all my message values to the phrase app magic string when the locale file is loaded. 

The phraseapp editor js code picks up the strings just fine.

**Comment by jameschao** [comment]
Hi @BobReid - can you elaborate on the "phrase app magic string"? I'm not quite sure what that is so maybe I missed something.

**Comment by FRSgit** [comment]
Hello everybody! I've just taken over maintaining of `react-intl-phraseapp` repository and saw this - fairly old - issue on our library's board. My question is: does this still is an issue? Can anybody point me in the direction where it breaks now?

I see that there were some considerations about how the `react-intl-phraseapp` should connect with `react-intl` and I'm more than happy for follow on these, just need to know what are the expectations. This would be a big change on our side and need to be researched & planned correctly. So if any of you want to help us (Phrase) with that and be a part of bringing in any improvements, you're very welcome.
Any inputs from theoretical insights to direct work on PRs will help us a lot, so please don't hesitate to write down what's your expectations are here.
Cheers! 🚀

**Comment by FRSgit** [comment]
Closing this one as a stale. Possible rewrite with usage of `useIntl` will be continued as a part of #42
