### ISSUE TITLE
Can you cut a release following my PR?

### ISSUE THREAD

**Issue by llimllib** [phrase/react-intl-phraseapp#27]
We updated our create-react-app app to point to master, but create-react-app basically does not work (without serious handholding) with packages that are not published to npm. It would be super helpful if you could release 0.4.1.

If I can help I would be happy to do so

**Comment by theSoenke** [comment]
Hi, I've just published v0.4.1. Thanks for the suggestion

**Comment by llimllib** [comment]
Appreciate your quick responses, thanks
