### ISSUE TITLE
Do not seems to work with injectIntl hoc

### ISSUE THREAD

**Issue by moimael** [phrase/react-intl-phraseapp#3]
Hi,

I'm trying to integrate this plugin into our react-intl localized app and it seems like it doesn't work with injectIntl. Any tips ?

Thanks !

**Comment by timleers** [comment]
Hi @moimael 
you're right, unfortunately the plugin doesn't support injectIntl for now. We will add this feature in the future but cant estimate it right now.

If you like to support us feel free to share an example of the usage at https://github.com/phrase/react-intl-phraseapp-demo or even make a pr with an implementation.

We will keep you up to date on this issue.
Bests,
Tim

**Comment by moimael** [comment]
Any news on this ?

**Comment by Gcampes** [comment]
We need that, please

**Comment by moimael** [comment]
@theSoenke Thanks a lot, I'm trying to use it in our app, but why are you using a different api than react-intl ?

That seems like a lot of unnecessary work to move to this.

Instead of a translate prop, could we get the same function as react-intl ? (A prop this shape: `{intl: { formatMessage, formatDate, ... }}`)

**Comment by moimael** [comment]
Also when using translate and disabling the phraseapp context editor, I get an error: 

`react-intl-phraseapp.js:1523 Uncaught TypeError: Cannot read property 'prefix' of undefined`

Which makes sense since phraseapp is not enabled in the env I tested it. I still expect my page to load though.

**Comment by moimael** [comment]
Even if I specify a prefix and suffix, it breaks completely with translation not being displayed. Seems like it hasn't been tested with the in context editor disabled.
