### ISSUE TITLE
Can't disable PHRASEAPP

### ISSUE THREAD

**Issue by demkovych** [phrase/react-intl-phraseapp#34]
I tried to setup in-content only in development env:
```
 <script>
      window.PHRASEAPP_ENABLED = false; // Here will be true/false
      window.PHRASEAPP_CONFIG = {
        projectId: 'xxx',
        prefix: '[[__',
        suffix: '__]]',
        fullReparse: true
      };
</script>
```

 but I got an error:

`TypeError: Cannot read property 'apply' of undefined`

![image](https://user-images.githubusercontent.com/43744925/73743129-2f037b80-474e-11ea-8fe9-587347440a9a.png)

Codesandbox example: https://codesandbox.io/s/reactredux-wcjy9

**Comment by demkovych** [comment]
How to use phraseapp in react without in-content editor?

**Comment by theSoenke** [comment]
Hi @demkovych, I'm currently looking what is causing the error here. The InContext-Editor is only there to to provide a simpler way to edit translation directly in the application. For production you would have to sync the translations e.g. with our [client](https://phrase.com/cli/) and embed the translation files in your application

**Comment by FRSgit** [comment]
Hello @demkovych!
Sorry for the delay in the response you have encountered here 😞

Can you please describe your use case more widely? What are you trying to achieve?

Please try not to set `window.PHRASEAPP_ENABLED` directly, but by passing `phraseEnabled` config option set to `false` to `react-intl-phraseapp` initialize function. Like this:

```javascript 
initializePhraseAppEditor({
        phraseEnabled: true, // this value gets appended to `window.PHRASEAPP_ENABLED` by `react-intl-phraseapp` library
        projectId: 'xxx',
        prefix: '[[__',
        suffix: '__]]',
        fullReparse: true
});
```

If the issue still occurs for you after making the changes described above, please try to upgrade `react-intl-phraseapp` library to the newest version (we have shipped some fixes recently).

Hope that will help you, please don't hesitate to hit us back with the feedback! 🚀

**Comment by FRSgit** [comment]
@demkovych Do you still encounter the issue? If not, I'll close the issue at the end of this week

**Comment by FRSgit** [comment]
Hey @demkovych! Closing this issue as resolved, cheers!
