### ISSUE TITLE
ICU Message syntax with in-context editor

### ISSUE THREAD

**Issue by amosbastian** [phrase/react-intl-phraseapp#41]
Sent an email about this to Phrase's support but they told me to create an issue here:

If the translation is something using ICU Message syntax, so for example `{isMobileResolution, select, true {Short text} false {Longer text that only works on desktop}}`, then the in-context editor shows this literal string. Is there a way to format this correctly / set a value for `isMobileResolution`?

**Comment by FRSgit** [comment]
You might've faced a bug in the ICE, let mi investigate that one - I will come back to you whenever I have any solution!

**Comment by amosbastian** [comment]
Did you find anything? @FRSgit

**Comment by gustavnikolaj** [comment]
Any updates here?

I'm hitting the same issue, although it is not using the react-intl-phraseapp library, but the ICE itself. This is the first result when I'm searching for reports.
