### ISSUE TITLE
useIntl not exported

### ISSUE THREAD

**Issue by amosbastian** [phrase/react-intl-phraseapp#42]
In some places in our app we want to use a string instead of a JSX element and so we are importing `useIntl` from `react-intl` and using `formatMessage` directly.

```typescript
import { useIntl } from "react-intl";

const { formatMessage, formatNumber } = useIntl();
...
<>
  { formatMessage({ id: "my-id" }) }
</>
```

Now we want to use your in-context editor but you don't export `useIntl` from `react-intl-phraseapp`. Does this mean we have to replace `formatMessage` everywhere with `FormattedMessage` or is there a way to use `formatMessage` anyway?

**Comment by FRSgit** [comment]
Hey @amosbastian!
Unfortunately, we do not support usage of `react-intl` via `useIntl` hook. For now to use our library you need to always inject it with use of `injectIntl`.
It's possible to call `formatMessage` method, but only through components props, please have a look at [the example in our demo repository.](https://github.com/phrase/react-intl-phraseapp-demo/blob/master/src/App.js#L20)

Please give me a sign if that is enough for you use case! If not, do you suggest any changes we should do to our library? Have a nice weekend!

**Comment by amosbastian** [comment]
Ok we messaged to create a workaround by creating our own hook that could do this. Would be nice if this was included out of the box, though!

**Comment by FRSgit** [comment]
Good work! We will reconsider adding `useIntl` hook to our library.
Can you please share the code you're written to overcome the issue? It might help us understand you use-case better 👀

**Comment by jbruck-fs** [comment]
It would be really nice to have the `useIntl` hook in the library.

👍 +1

**Comment by jorisw** [comment]
We need `useIntl` too, in order to use formatted messages as localized URL slugs. Example:

```ts
import { Route, routes } from 'config'
import React from 'react'
import { useIntl } from 'react-intl'
import { NavLink } from 'react-router-dom'

export const Navigation: React.FC = () => {
  const { formatMessage, locale } = useIntl()

  const localizeRouteKey = (path: string): string => {
    return `/${locale}` + formatMessage({ id: path })
  }

  return (
    <ul className={'list-container'}>
      {routes.map(({ routeKey, titleKey }: Route) => (
        <li key={routeKey} className={'list-item'}>
          <NavLink
            exact
            className={'link-primary'}
            activeClassName={'link-active'}
            to={localizeRouteKey(routeKey)}
          >
            {formatMessage({ id: titleKey })}
          </NavLink>
        </li>
      ))}
    </ul>
  )
}```

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20) and we can take more direct action toward finding a solution.
