### ISSUE TITLE
TypeError when used in a TypeScript environment

### ISSUE THREAD

**Issue by jorisw** [phrase/react-intl-phraseapp#48]
Hi,

Replacing the imports of `FormattedMessage` with ones from `react-intl-phraseapp`, yields the following type error in our TypeScript React app:

```
TypeError: The superclass is not an object.

(anonymous function)
http://localhost:3002/static/js/1.chunk.js:212761:22
  212758 |       s = r(2),
  212759 |       i = r(0);
  212760 | 
> 212761 | class o extends s.FormattedHTMLMessage {
         |                  ^
  212762 |   render() {
  212763 |     return i.isPhraseEnabled() ? n.createElement("span", null, i.escapeId(this.props.id)) : super.render();
  212764 |   }
```

Snippet from our root App component:

```ts
import { initializePhraseAppEditor } from 'react-intl-phraseapp'

...

const phraseAppConfig = {
  projectId: 'abcdefghijklmnopqrstuvwxyz',
  phraseEnabled: true,
  prefix: '[[__',
  suffix: '__]]',
  fullReparse: true,
}

initializePhraseAppEditor(phraseAppConfig)
```

Snippet from a component using `FormattedMessage`: 

```tsx
import { Button } from 'our-design-system'
import React from 'react'
import { FormattedMessage } from 'react-intl-phraseapp'

export const RequestOffer: React.FC = () => {
  return (
    <>
      <h1>
        <FormattedMessage id="request_offer.title" />
      </h1>
      <Button variant="primary">
        <FormattedMessage id="request_offer.title" />
      </Button>
    </>
  )
}
```

Relevant packages:
```
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-intl": "^4.5.0",
    "react-intl-phraseapp": "^2.1.1",
    "typescript": "^3.8.3"
```

**Comment by FRSgit** [comment]
Hey @jorisw,

Unfortunately, our package doesn't support `react-intl@4.0.0+` yet and it seems that some internal changes of `FormattedMessage` component within `react-intl` did break our code.

There are plans on our side to work on this (support for newer versions of `react-intl`), but first we need to decide on the full scope of changes (we are considering few features which could be changed/added). So in the short term I would suggest downgrading `react-intl` to version `3.12.1` which is the last on from `^3.0.0` branch of `react-intl`.

Ofc the PRs are more than welcome as well!

Is my solution something which would work for you (at least for the time being)?

**Comment by jorisw** [comment]
Indeed it works with the downgraded `react-intl`, thanks.
