### ISSUE TITLE
Missing support for useIntl hook

### ISSUE THREAD

**Issue by Jordaneisenburger** [phrase/react-intl-phraseapp#75]
Hi,

We are using the `useIntl()` hook from `react-intl` but it doesnt seem to be supported/exposed in `react-intl-phraseapp`. Is this planned to be added as we are not using the `FormattedMessage` component.

Thanks!

**Comment by forelabs** [comment]
Hi Jordan,

Thanks for reaching out to us.

I forwarded your question to the Engineering Team and will let you know as soon as I hear back from them.

Best,
Domenica from the Phrase Technical Support Team

*Comment by Domenica Barone*

**Comment by Szymon-dziewonski** [comment]
Hello @Jordaneisenburger , your PR was merged and released in version 3.0.2, I've tested it personally and it worked as expected. 
Can you please explain me what would be expected outcome, how would like to use `useIntl()`? 

Thank you in advance

**Comment by Jordaneisenburger** [comment]
Hi @Szymon-dziewonski,

The PR wasn't mine btw. But my problem is in the below scenario:

```
//component.js
import { useIntl } from 'react-intl-phraseapp';

const Component = () => {
const { formatMessage } = useIntl();

const label = formatMessage({
    id: 'Error.SomethingWentWrong',
    defaultMessage: 'Something went wrong'
})

return label 
//This is pseudo code so might have a typo
}
```
Looking at https://github.com/phrase/react-intl-phraseapp/blob/master/src/index.ts useIntl is not being wrapped or exported like you did for `FormattedMessage `.

**Comment by Szymon-dziewonski** [comment]
@Jordaneisenburger Ah sorry, my bad, I just remembered your avatar from that PR :)
Thank you for your example code, I understand use case here. 
Will get back to you shortly with answer, if and when we would add support like that

**Comment by Szymon-dziewonski** [comment]
@Jordaneisenburger we will try to add support, I will work on it in next days, thank you for your time and effort :)

**Comment by Jordaneisenburger** [comment]
@Szymon-dziewonski that would be amazing, our teams are really looking forward to be able to use the In Context Editor functionality. When you have a beta or alpha release please let me know so I can help test it for you on an actual project.

**Comment by Jordaneisenburger** [comment]
@Szymon-dziewonski  any status on this ?

**Comment by Szymon-dziewonski** [comment]
@Jordaneisenburger Im sorry that this issue was not tackled yet, unfortunately I'm no longer working in Phrase, hopefully @theSoenke or @Varpusparvi might/will help you :)

**Comment by Jordaneisenburger** [comment]
@theSoenke when do you expect this to be delivered and if doing an official request from our enterprise licence to get this issue prioritized please let me know ?

**Comment by Varpusparvi** [comment]
@Jordaneisenburger We will take a look into this in the next 2 weeks, thanks for raising this.

**Comment by Varpusparvi** [comment]
@Jordaneisenburger There was a new release done. Let us know if this helps you and we can close the issue.
