### ISSUE TITLE
Bug/defaultMessage does not work

### ISSUE THREAD

**Issue by MylesWardell** [phrase/react-intl-phraseapp#79]
#### Issue
Using the `defaultMessage` prop on `FormattedMessage` does not add the translation to the phrase nor does it show up when logged in.

#### Example of UI
![image](https://user-images.githubusercontent.com/55673046/201586657-f79291cd-040f-4080-a2a6-04041789534f.png)

#### Example Of Code
```typescript
<FormattedMessage id="dashboard.kinesisCard.marketing.title" defaultMessage="Kinesis Card" />
```

#### Explaination
I am about to embark on a huge localization journey. I was hoping to use defaultMessage to simplify the developer experience and just get them to copy paste the existing code into the defaultMessage. Instead I will have to get them to open the phrase in-context editor and paste and save it their. 

Ideally when I open the in-context editor and any keys dont exist on the server but exist via default message it automatically gets saved in bulk.

Am I missing something?

**Comment by Varpusparvi** [comment]
@MylesWardell  Currently we only support the `formatMessage` function from `useIntl`, but not the `<FormattedMessage/>` component

**Comment by MylesWardell** [comment]
I'll try again using that method 👍

**Comment by MylesWardell** [comment]
@Varpusparvi For my problem their doesn't appear to change if I use `formatMessage()` over `<FormattedMessage />`. Both do not add the `defaultMessage` to the Phrase Strings store.

Is their a reason you recommend this method?

```typescript
const { formatMessage } = useIntl()
return <Title>{formatMessage({ id: 'dashboard.kinesisCard.marketing.title', defaultMessage: 'Kinesis Card' })} </Title>
```

**Comment by MylesWardell** [comment]
> @MylesWardell Currently we only support the `formatMessage` function from `useIntl`, but not the `<FormattedMessage/>` component

Also in your readme you are importing `<FormattedMessage />`
![image](https://user-images.githubusercontent.com/55673046/201822623-79e84c8e-bd2f-4d27-a01b-c2d607992e08.png)

**Comment by Varpusparvi** [comment]
@MylesWardell Oh looks like you are right, we do support it 🤔 

Maybe I didn't understand your issue. When you save a translation for a key via the in context editor will it be saved to the database? 
If not, could you check the network tab of chrome tools if there is something we could use to debug.
If yes, is your issue about a new feature which would create all keys that are not yet saved to the database?

We currently don't have a way to create the keys in batch from the in context editor, but what you could do is add them to a file and upload them to your project.

**Comment by MylesWardell** [comment]
> @MylesWardell Oh looks like you are right, we do support it 🤔 
> 
> Maybe I didn't understand your issue. When you save a translation for a key via the in context editor will it be saved to the database? 
> If not, could you check the network tab of chrome tools if there is something we could use to debug.
> If yes, is your issue about a new feature which would create all keys that are not yet saved to the database?
> 
> We currently don't have a way to create the keys in batch from the in context editor, but what you could do is add them to a file and upload them to your project.

I feel like I can potentially get a regex on our code base that goes through and saves the default message to the key. I guess this is less a bug and more of a feature request. It would be nice if default values automatically updated the phrase strings default language database. 

Thank you for the help you can leave this as a feature request or close the issue 👍

**Comment by Varpusparvi** [comment]
@MylesWardell Thanks, it is an interesting idea, I will raise this as a topic for further ICE development 👍 
For now you will definitely be better off uploading them as a file until we could develop this feature.
