### ISSUE TITLE
syntax error in IE: usage of class

### ISSUE THREAD

**Issue by maxcc0** [phrase/react-intl-phraseapp#8]
The bundled js has `class`  due to which it does not work in IE. Transpiling it should fix it.

**Comment by theSoenke** [comment]
Hi @maxcc0 thanks for reporting it. I will have a closer look at this

**Comment by maxcc0** [comment]
Perfect. Thanks!

**Comment by theSoenke** [comment]
I have now published v0.2.1 which should resolve it. Let me know in case you experience still any issue
