### ISSUE TITLE
The injectIntl HOC is incorrectly typed

### ISSUE THREAD

**Issue by MylesWardell** [phrase/react-intl-phraseapp#85]
Its injections injects an object called intl with two functions on it not injecting just the fuctions and the formatMessage function has incorrect parameters. (ie formatMessage can have a 2nd param with values and a default message

![image](https://user-images.githubusercontent.com/55673046/220249340-e8fe94d3-885d-4e78-adb2-3acbfecb0910.png)

**Comment by Varpusparvi** [comment]
@MylesWardell Does this fix your issue? https://github.com/phrase/react-intl-phraseapp/pull/86

**Comment by MylesWardell** [comment]
No it doesnt we are trying to translate for the few legacy class components we have remaining. Can you update your react-intl library to contain the latest types from them?

**Comment by MylesWardell** [comment]
```typescript
import * as React from 'react';
import { IntlShape } from '../types';
export declare const Provider: React.Provider<IntlShape>;
export declare const Context: React.Context<IntlShape>;
export interface Opts<IntlPropName extends string = 'intl', ForwardRef extends boolean = false> {
    intlPropName?: IntlPropName;
    forwardRef?: ForwardRef;
    enforceContext?: boolean;
}
export type WrappedComponentProps<IntlPropName extends string = 'intl'> = {
    [k in IntlPropName]: IntlShape;
};
export type WithIntlProps<P> = Omit<P, keyof WrappedComponentProps> & {
    forwardedRef?: React.Ref<any>;
};
export default function injectIntl<IntlPropName extends string = 'intl', P extends WrappedComponentProps<IntlPropName> = WrappedComponentProps<any>>(WrappedComponent: React.ComponentType<P>, options?: Opts<IntlPropName, false>): React.FC<WithIntlProps<P>> & {
    WrappedComponent: React.ComponentType<P>;
};
export default function injectIntl<IntlPropName extends string = 'intl', P extends WrappedComponentProps<IntlPropName> = WrappedComponentProps<any>, T extends React.ComponentType<P> = any>(WrappedComponent: React.ComponentType<P>, options?: Opts<IntlPropName, true>): React.ForwardRefExoticComponent<React.PropsWithoutRef<WithIntlProps<React.PropsWithChildren<P>>> & React.RefAttributes<T>> & {
    WrappedComponent: React.ComponentType<P>;
};
//# sourceMappingURL=injectIntl.d.ts.map
```

**Comment by MylesWardell** [comment]
`react-intl\src\components\injectIntl.d.ts`

**Comment by MylesWardell** [comment]
While this works on our environment we cannot use the phrase editor to update the text as we are not using the phrase-react export.

**Comment by Varpusparvi** [comment]
Could you provide code example how you want to use this?

**Comment by MylesWardell** [comment]
Usage would be in legacy components. We only have maybe 4-8 components still using class structure but we cant use hooks inside them.

```typescript
import React, { Component } from "react";
import { WrappedComponentProps, injectIntl } from "react-intl-phraseapp";

interface LegacyComponentProps {
  foo: string;
}

type Props = LegacyComponentProps & WrappedComponentProps;

class LegacyComponent extends Component<Props, {}> {
  render() {
    return (
      <div>
        {this.props.intl.formatMessage({ id: "foo", defaultMessage: "bar" })}
      </div>
    );
  }
}

export default injectIntl(LegacyComponent);
```

**Comment by MylesWardell** [comment]
What we ended up doing was just using this and adding the keys manually
```typescript
import React, { Component } from "react";
import { WrappedComponentProps, injectIntl } from "react-intl";

interface LegacyComponentProps {
  foo: string;
}

type Props = LegacyComponentProps & WrappedComponentProps;

class LegacyComponent extends Component<Props, {}> {
  render() {
    return (
      <div>
        {this.props.intl.formatMessage({ id: "foo", defaultMessage: "bar" })}
      </div>
    );
  }
}

export default injectIntl(LegacyComponent);
```

**Comment by itsahsiao** [comment]
@MylesWardell Apologies for the delay in getting back to you. I'm really glad you were able to figure out a solution ⭐ 

Since we aren't using the latest version of react-intl, then I'm guessing that's why you had to implement a workaround as provided above. Would updating to the latest version help so you don't have to do that manually? 

Please feel free to contribute to our codebase by opening a Pull Request. Such changes and improvements are always welcome and would help out others who are using react-intl with Phrase.

**Comment by Varpusparvi** [comment]
@MylesWardell Hey! We released a new major version 4.0.0 with upgraded packeges and improved typings. We also tried to cover your use case with our `examples/demo`.

Could you check if this release fixes your issues?

**Comment by MylesWardell** [comment]
Ill close once I test but currently this issue #103 is blocking

**Comment by itsahsiao** [comment]
@MylesWardell We've already fixed #103 with #104. Just curious if you're still experiencing issues?

**Comment by MylesWardell** [comment]
I think we just removed the class components from our application so this is no longer necessary. I would have to create a tests app t test it.

**Comment by itsahsiao** [comment]
Thanks for letting us know. We'll be closing this issue then :) Feel free to re-open this or open a new issue if you experience any problems.
